services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_KEY64: "sshkey64"
    ports:
      - "3000:3000"
    links:
      - redis
    volumes:
      - slettmeg:/db
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  slettmeg:
    driver: local